// <auto-generated />
using System;
using GroupBy.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupBy.Data.Migrations
{
    [DbContext(typeof(GroupByDbContext))]
    [Migration("20230830153650_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgreementVolunteer", b =>
                {
                    b.Property<Guid>("AgreementsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteersAcceptedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgreementsId", "VolunteersAcceptedId");

                    b.HasIndex("VolunteersAcceptedId");

                    b.ToTable("AgreementVolunteer");
                });

            modelBuilder.Entity("ElementGroup", b =>
                {
                    b.Property<Guid>("ElementsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ElementsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("ElementGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.AccountingBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookIdentificator")
                        .HasColumnType("int");

                    b.Property<int>("BookOrderNumberId")
                        .HasColumnType("int");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("BookIdentificator", "BookOrderNumberId");

                    b.HasIndex("RelatedGroupId");

                    b.ToTable("AccountingBooks");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("VolunteerId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedProjectId");

                    b.ToTable("Elements");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Element");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.FinancialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("RelatedDocumentId");

                    b.HasIndex("RelatedProjectId");

                    b.ToTable("FinancialRecords");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FinancialRecord");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.GroupsPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Books")
                        .HasColumnType("bit");

                    b.Property<bool?>("EditElements")
                        .HasColumnType("bit");

                    b.Property<bool?>("EditMembers")
                        .HasColumnType("bit");

                    b.Property<bool?>("EditPosition")
                        .HasColumnType("bit");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Invitation")
                        .HasColumnType("bit");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Resolutions")
                        .HasColumnType("bit");

                    b.Property<bool?>("SeeElements")
                        .HasColumnType("bit");

                    b.Property<bool?>("Subgroups")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("GroupId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("InventoryBooks");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryBookRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Income")
                        .HasColumnType("bit");

                    b.Property<Guid>("InventoryBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("InventoryBookId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SourceId");

                    b.ToTable("InventoryBookRecords");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryItemSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItemSources");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InvitationToGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvitedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InviterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvitedId");

                    b.HasIndex("InviterId");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("InvitationToGroups");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HigherPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HigherPositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.PositionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointingResolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DismissingResolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("VolunteerId", "Id");

                    b.HasIndex("AppointingResolutionId");

                    b.HasIndex("DismissingResolutionId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RelatedGroupId");

                    b.ToTable("PositionRecords");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Independent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("ProjectGroupId")
                        .IsUnique()
                        .HasFilter("[ProjectGroupId] IS NOT NULL");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HigherRankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HigherRankId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ReplacedByTokenId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.RegistrationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetRankId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Code");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("TargetRankId");

                    b.ToTable("RegistrationCodes");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Resolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LegislatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LegislatorId");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.TODOListElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("TODOListElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TODOListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsigneeId");

                    b.HasIndex("TODOListElementId");

                    b.HasIndex("TODOListId");

                    b.ToTable("TODOListElements");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("GroupVolunteer", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("GroupVolunteer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RemainderVolunteer", b =>
                {
                    b.Property<Guid>("RemaindersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteersAcceptedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RemaindersId", "VolunteersAcceptedId");

                    b.HasIndex("VolunteersAcceptedId");

                    b.ToTable("RemainderVolunteer");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Document", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.Element");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Document");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Remainder", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.Element");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Remainder");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.TODOList", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.Element");

                    b.HasDiscriminator().HasValue("TODOList");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.FinancialIncomeRecord", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.FinancialRecord");

                    b.Property<decimal?>("Dotation")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("EarningAction")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MembershipFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("OnePercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Other")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ProgramFee")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable("FinancialRecords", t =>
                        {
                            t.Property("Other")
                                .HasColumnName("FinancialIncomeRecord_Other");
                        });

                    b.HasDiscriminator().HasValue("FinancialIncomeRecord");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.FinancialOutcomeRecord", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.FinancialRecord");

                    b.Property<decimal?>("Accommodation")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Food")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Insurance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Inventory")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Material")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Other")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Service")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Transport")
                        .HasColumnType("decimal(10, 2)");

                    b.HasDiscriminator().HasValue("FinancialOutcomeRecord");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.AccountingDocument", b =>
                {
                    b.HasBaseType("GroupBy.Domain.Entities.Document");

                    b.HasDiscriminator().HasValue("AccountingDocument");
                });

            modelBuilder.Entity("AgreementVolunteer", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AgreementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteersAcceptedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElementGroup", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Element", null)
                        .WithMany()
                        .HasForeignKey("ElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.AccountingBook", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Group", "RelatedGroup")
                        .WithMany("AccountingBooks")
                        .HasForeignKey("RelatedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "RelatedVolunteer")
                        .WithOne("Identity")
                        .HasForeignKey("GroupBy.Domain.Entities.ApplicationUser", "VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedVolunteer");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Element", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Project", "RelatedProject")
                        .WithMany("RelatedElements")
                        .HasForeignKey("RelatedProjectId");

                    b.Navigation("RelatedProject");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.FinancialRecord", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.AccountingBook", "Book")
                        .WithMany("Records")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.AccountingDocument", "RelatedDocument")
                        .WithMany("RelatedRecords")
                        .HasForeignKey("RelatedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Project", "RelatedProject")
                        .WithMany("RelatedFinnancialRecords")
                        .HasForeignKey("RelatedProjectId");

                    b.Navigation("Book");

                    b.Navigation("RelatedDocument");

                    b.Navigation("RelatedProject");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Group", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Group", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId");

                    b.Navigation("Owner");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.GroupsPermissions", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Group", "Group")
                        .WithMany("Permissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryBook", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Group", "RelatedGroup")
                        .WithOne("InventoryBook")
                        .HasForeignKey("GroupBy.Domain.Entities.InventoryBook", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryBookRecord", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.InventoryBook", "Book")
                        .WithMany("Records")
                        .HasForeignKey("InventoryBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.InventoryItem", "Item")
                        .WithMany("History")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.InventoryItemSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Document");

                    b.Navigation("Item");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InvitationToGroup", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Invited")
                        .WithMany("InvitationsToGroup")
                        .HasForeignKey("InvitedId");

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Inviter")
                        .WithMany("YourInvitations")
                        .HasForeignKey("InviterId");

                    b.HasOne("GroupBy.Domain.Entities.Group", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId");

                    b.Navigation("Invited");

                    b.Navigation("Inviter");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Position", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Position", "HigherPosition")
                        .WithMany()
                        .HasForeignKey("HigherPositionId");

                    b.Navigation("HigherPosition");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.PositionRecord", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Resolution", "AppointingResolution")
                        .WithMany()
                        .HasForeignKey("AppointingResolutionId");

                    b.HasOne("GroupBy.Domain.Entities.Resolution", "DismissingResolution")
                        .WithMany()
                        .HasForeignKey("DismissingResolutionId");

                    b.HasOne("GroupBy.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Group", "RelatedGroup")
                        .WithMany()
                        .HasForeignKey("RelatedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Person")
                        .WithMany("PositionHistory")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointingResolution");

                    b.Navigation("DismissingResolution");

                    b.Navigation("Person");

                    b.Navigation("Position");

                    b.Navigation("RelatedGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Project", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Group", "ParentGroup")
                        .WithMany("ProjectsRealisedInGroup")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Group", "ProjectGroup")
                        .WithOne("RelatedProject")
                        .HasForeignKey("GroupBy.Domain.Entities.Project", "ProjectGroupId");

                    b.Navigation("Owner");

                    b.Navigation("ParentGroup");

                    b.Navigation("ProjectGroup");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Rank", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Rank", "HigherRank")
                        .WithMany()
                        .HasForeignKey("HigherRankId");

                    b.Navigation("HigherRank");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("OwnerId");

                    b.HasOne("GroupBy.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId");

                    b.Navigation("Owner");

                    b.Navigation("ReplacedByToken");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.RegistrationCode", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Owner")
                        .WithMany("RegistrationCodes")
                        .HasForeignKey("OwnerId");

                    b.HasOne("GroupBy.Domain.Entities.Group", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Rank", "TargetRank")
                        .WithMany()
                        .HasForeignKey("TargetRankId");

                    b.Navigation("Owner");

                    b.Navigation("TargetGroup");

                    b.Navigation("TargetRank");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Resolution", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Group", "Group")
                        .WithMany("Resolutions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Legislator")
                        .WithMany()
                        .HasForeignKey("LegislatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Legislator");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.TODOListElement", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Volunteer", "Asignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AsigneeId");

                    b.HasOne("GroupBy.Domain.Entities.TODOListElement", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("TODOListElementId");

                    b.HasOne("GroupBy.Domain.Entities.TODOList", null)
                        .WithMany("List")
                        .HasForeignKey("TODOListId");

                    b.Navigation("Asignee");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Volunteer", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Rank", "Rank")
                        .WithMany("VolunteersRanked")
                        .HasForeignKey("RankId");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("GroupVolunteer", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RemainderVolunteer", b =>
                {
                    b.HasOne("GroupBy.Domain.Entities.Remainder", null)
                        .WithMany()
                        .HasForeignKey("RemaindersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupBy.Domain.Entities.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteersAcceptedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.AccountingBook", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Group", b =>
                {
                    b.Navigation("AccountingBooks");

                    b.Navigation("ChildGroups");

                    b.Navigation("InventoryBook");

                    b.Navigation("Permissions");

                    b.Navigation("ProjectsRealisedInGroup");

                    b.Navigation("RelatedProject");

                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryBook", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Project", b =>
                {
                    b.Navigation("RelatedElements");

                    b.Navigation("RelatedFinnancialRecords");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Rank", b =>
                {
                    b.Navigation("VolunteersRanked");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.TODOListElement", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.Volunteer", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Identity");

                    b.Navigation("InvitationsToGroup");

                    b.Navigation("OwnedGroups");

                    b.Navigation("OwnedProjects");

                    b.Navigation("PositionHistory");

                    b.Navigation("RegistrationCodes");

                    b.Navigation("YourInvitations");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.TODOList", b =>
                {
                    b.Navigation("List");
                });

            modelBuilder.Entity("GroupBy.Domain.Entities.AccountingDocument", b =>
                {
                    b.Navigation("RelatedRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
