name: Build, test and pack application

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: false
        type: string
        default: GroupBy.Web.API
      ONLY_BUILD:
        required: false
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      if: ${{ !inputs.ONLY_BUILD }}
      run: dotnet publish --no-restore -c Release
    - name: Pack
      if: ${{ !inputs.ONLY_BUILD }}
      run: tar czvf "${{ inputs.APPLICATION_NAME }}.tar.gz" ${{ inputs.APPLICATION_NAME }}/bin/Release/net7.0/publish
    - name: Clean build dir
      if: ${{ !inputs.ONLY_BUILD }}
      run: rm -r ${{ inputs.APPLICATION_NAME }}/bin/Release/net7.0/publish
    - name: Upload artifact
      if: ${{ !inputs.ONLY_BUILD }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.APPLICATION_NAME }}
        path: ${{ inputs.APPLICATION_NAME }}.tar.gz