name: Create API documentation

on:
  workflow_call:
    inputs:
      SWASHBUCKLE_DOTNET_CORE_VERSION:
        required: true
        type: string
        default: 7.0.x
      SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION:
        required: true
        type: string
        default: 6.5.0
      API_IMPORT_SPECIFICATION_PATH:
        required: true
        type: string
        default: swagger.json
      API_IMPORT_DLL:
        required: true
        type: string
        default: GroupBy.Web.API/bin/Release/net7.0/publish/GroupBy.Web.API.dll
      API_IMPORT_VERSION:
        required: true
        type: string
        default: groupbydoc

jobs:
  create-api-doc:
    name: Create OpenAPI documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Setup SwashBuckle .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.SWASHBUCKLE_DOTNET_CORE_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish --no-restore -c Release
      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ inputs.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Generate Open API Specification Document
        run: swagger tofile --output "${{ inputs.API_IMPORT_SPECIFICATION_PATH }}" "${{ inputs.API_IMPORT_DLL }}" "${{ inputs.API_IMPORT_VERSION }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenAPIDoc
          path: ${{ inputs.API_IMPORT_SPECIFICATION_PATH }}