name: Create DEV release package

on:
  workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  APPLICATION_NAME: GroupBy.Web.API
  SWASHBUCKLE_DOTNET_CORE_VERSION: 7.0.x
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
  API_IMPORT_SPECIFICATION_PATH: swagger.json
  API_IMPORT_DLL: GroupBy.Web.API/bin/Release/net7.0/publish/GroupBy.Web.API.dll
  API_IMPORT_VERSION: groupbydoc

jobs:
  build:
    name: Build, test, pack
    runs-on: ubuntu-latest
    steps:
      - name: Build, test, pack
        uses: ./.github/workflows/build-pack.yml
        with:
          APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
          ONLY_BUILD: false

  build-release:
    name: Build release docker image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker build
        uses: ./.gtihub/workflows/build-docker.yml
        with:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          DEV_RELEASE: true
          APPLICATION_NAME: ${{ env.APPLICATION_NAME }}

  create-api-doc:
    name: Create OpenAPI documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create OpenAPI documentation
        uses: ./.github/workflows/create-api-doc.yml
        with:
          SWASHBUCKLE_DOTNET_CORE_VERSION: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}
          SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}
          API_IMPORT_SPECIFICATION_PATH: ${{ env.API_IMPORT_SPECIFICATION_PATH }}
          API_IMPORT_DLL: ${{ env.API_IMPORT_DLL }}
          API_IMPORT_VERSION: ${{ env.API_IMPORT_VERSION }}
  generate-changelog:
    name: Generate changelog
    needs: [build-release, create-api-doc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Genereate changelog
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: CHANGELOG.md