name: Create DEV release package

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  APPLICATION_NAME: GroupBy.Web.API
  SWASHBUCKLE_DOTNET_CORE_VERSION: 7.0.x
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
  API_IMPORT_SPECIFICATION_PATH: swagger.json
  API_IMPORT_DLL: GroupBy.Web.API/bin/Release/net7.0/publish/GroupBy.Web.API.dll
  API_IMPORT_VERSION: groupbydoc

jobs:
  build:
    name: Build, test, pack
    uses: ./.github/workflows/build-pack.yml
    with:
      APPLICATION_NAME: GroupBy.Web.API
      ONLY_BUILD: false

  build-release:
    name: Build release docker image
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-docker.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DEV_RELEASE: true
      APPLICATION_NAME: GroupBy.Web.API

  create-api-doc:
    name: Create OpenAPI documentation
    needs: build
    uses: ./.github/workflows/create-api-doc.yml
    with:
      SWASHBUCKLE_DOTNET_CORE_VERSION: 7.0.x
      SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
      API_IMPORT_SPECIFICATION_PATH: swagger.json
      API_IMPORT_DLL: GroupBy.Web.API/bin/Release/net7.0/publish/GroupBy.Web.API.dll
      API_IMPORT_VERSION: groupbydoc

  generate-changelog:
    name: Generate changelog
    needs: [build-release, create-api-doc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Genereate changelog
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: CHANGELOG.md