name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    uses: ./.github/workflows/build-pack.yml
    with:
      APPLICATION_NAME: GroupBy.Web.API
      ONLY_BUILD: true
